-- V1__initial_schema.sql

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Create roles
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user WITH LOGIN PASSWORD '${app_user_password}';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'shhmods_admin') THEN
    CREATE ROLE shhmods_admin WITH LOGIN PASSWORD '${admin_password}';
  END IF;
END
$$;

-- ============================================================
-- 1. USERS
-- ============================================================
CREATE TABLE users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          VARCHAR(100) NOT NULL,
    external_user_id   VARCHAR(100) NOT NULL,
    username           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    status             VARCHAR(50)  DEFAULT 'ACTIVE',
    is_visible         BOOLEAN      DEFAULT TRUE,
    account_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, external_user_id)
);
CREATE INDEX idx_users_tenant_id ON users(tenant_id);

-- ============================================================
-- 2. CONTENT
-- ============================================================
CREATE TABLE content (
    content_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    VARCHAR(100) NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_text TEXT   NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    content_hash VARCHAR(255) NOT NULL,
    is_visible   BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_content_hash       ON content(content_hash);
CREATE INDEX idx_content_created_at ON content(created_at DESC);
CREATE INDEX idx_content_user_id    ON content(user_id);
CREATE INDEX idx_content_tenant_id  ON content(tenant_id);

-- ============================================================
-- 3. REPORT
-- ============================================================
CREATE TABLE report (
    report_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id       BIGINT NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
    reporter_id      BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    report_reason    TEXT   NOT NULL,
    status           VARCHAR(50) DEFAULT 'PENDING',
    reported_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    reporter_ip_hash VARCHAR(255)
);
ALTER TABLE report ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_report_content_id  ON report(content_id);
CREATE INDEX idx_report_reporter_id ON report(reporter_id);
CREATE INDEX idx_report_reported_at ON report(reported_at DESC);

-- ============================================================
-- 4. CONTENT_FLAG
-- ============================================================
CREATE TABLE content_flag (
    flag_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id   BIGINT NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
    flag_type    VARCHAR(50) NOT NULL,
    reason       TEXT   NOT NULL,
    status       VARCHAR(50) DEFAULT 'PENDING',
    report_count INT DEFAULT 0,
    flagged_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_flag_content_id    ON content_flag(content_id);
CREATE INDEX idx_flag_status        ON content_flag(status) WHERE status != 'RESOLVED';

-- ============================================================
-- 5. BANNED_WORD
-- ============================================================
CREATE TABLE banned_word (
    word_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      VARCHAR(100) NOT NULL DEFAULT 'GLOBAL',
    keyword        VARCHAR(255) NOT NULL,
    match_type     VARCHAR(50) DEFAULT 'EXACT_WORD_ONLY',
    severity_level INT DEFAULT 1,
    word_status    VARCHAR(50) DEFAULT 'ACTIVE',
    added_by       VARCHAR(255) DEFAULT 'SYSTEM',
    added_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, keyword)
);
CREATE INDEX idx_banned_word_trgm   ON banned_word USING GIN (keyword gin_trgm_ops);
CREATE INDEX idx_banned_word_tenant ON banned_word(tenant_id);

-- ============================================================
-- 6. OUTBOX_EVENT
-- ============================================================
CREATE TABLE outbox_event (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    payload        JSONB NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at   TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
CREATE INDEX idx_outbox_unprocessed ON outbox_event(created_at ASC) WHERE processed_at IS NULL;

-- ============================================================
-- 7. AUDIT_LOG
-- ============================================================
CREATE TABLE audit_log (
    audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type      VARCHAR(255) NOT NULL,
    action_details   TEXT,
    reference_type   VARCHAR(255) NOT NULL,
    reference_id     VARCHAR(255) NOT NULL,
    actor_id         BIGINT,
    actor_type       VARCHAR(50) DEFAULT 'SYSTEM',
    action_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 8. TENANT_CONFIG
-- ============================================================
CREATE TABLE tenant_config (
    tenant_id                 VARCHAR(100) PRIMARY KEY,
    weight_accurate_reports   DECIMAL(5,2) DEFAULT 5.0,
    weight_severity           DECIMAL(5,2) DEFAULT 1.0,
    weight_account_age        DECIMAL(5,2) DEFAULT 10.0,
    shadow_ban_threshold      INT          DEFAULT 10,
    report_threshold          INT          DEFAULT 3,
    burst_limit               INT          DEFAULT 3,
    sustained_limit           INT          DEFAULT 10,
    trgm_similarity_threshold DECIMAL(3,2) DEFAULT 0.35,
    created_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO tenant_config (tenant_id) VALUES ('GLOBAL');

-- ============================================================
-- 9. MODERATION LEDGER (V5)
-- ============================================================
CREATE TABLE moderation_event (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_hash VARCHAR(64) NOT NULL,
    normalized_text TEXT,
    signals JSONB NOT NULL,
    policy_version INT NOT NULL,
    decision VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_moderation_event_created_at_brin ON moderation_event USING BRIN(created_at);
CREATE INDEX idx_moderation_event_user_id ON moderation_event(user_id);

CREATE OR REPLACE FUNCTION prevent_ledger_tampering() RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Moderation ledger is immutable. UPDATE or DELETE operations are forbidden.';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_moderation_event_immutable
BEFORE UPDATE OR DELETE ON moderation_event
FOR EACH ROW EXECUTE FUNCTION prevent_ledger_tampering();

-- ============================================================
-- 10. TEMPORAL TRUST DECAY (V7)
-- ============================================================
CREATE TABLE trust_event (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    compartment VARCHAR(50) NOT NULL,
    penalty DECIMAL(10,2) NOT NULL,
    decay_rate DECIMAL(15,10) NOT NULL,
    occurred_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trust_event_user_id ON trust_event(user_id, compartment);

CREATE VIEW effective_trust AS
SELECT 
    user_id, 
    compartment,
    GREATEST(0.0, 100.0 - SUM(
        penalty * exp(-decay_rate * EXTRACT(EPOCH FROM (now() - occurred_at)))
    )) AS current_trust
FROM trust_event
GROUP BY user_id, compartment;

-- ============================================================
-- 11. GRAPH COORDINATION CLUSTERS (V6)
-- ============================================================
CREATE MATERIALIZED VIEW coordination_clusters AS
WITH recent_reports AS (
    SELECT r.reporter_id, c.user_id AS target_id
    FROM report r
    JOIN content c ON r.content_id = c.content_id
    WHERE r.reported_at > NOW() - INTERVAL '24 hours'
),
reporter_pairs AS (
    SELECT
        r1.reporter_id AS reporter_a,
        r2.reporter_id AS reporter_b,
        count(*) AS shared_targets
    FROM recent_reports r1
    JOIN recent_reports r2
      ON r1.target_id = r2.target_id
     AND r1.reporter_id < r2.reporter_id
    GROUP BY r1.reporter_id, r2.reporter_id
)
SELECT reporter_a, reporter_b, shared_targets
FROM reporter_pairs
WHERE shared_targets >= 3;

CREATE INDEX idx_coordination_reporter_a ON coordination_clusters(reporter_a);
CREATE INDEX idx_coordination_reporter_b ON coordination_clusters(reporter_b);

CREATE MATERIALIZED VIEW content_clusters AS
WITH recent_content AS (
    SELECT user_id, content_hash
    FROM content
    WHERE created_at > NOW() - INTERVAL '1 hour'
),
poster_pairs AS (
    SELECT
        c1.user_id AS poster_a,
        c2.user_id AS poster_b,
        count(*) AS shared_hashes
    FROM recent_content c1
    JOIN recent_content c2
      ON c1.content_hash = c2.content_hash
     AND c1.user_id < c2.user_id
    GROUP BY c1.user_id, c2.user_id
)
SELECT poster_a, poster_b, shared_hashes
FROM poster_pairs
WHERE shared_hashes >= 2;

CREATE INDEX idx_content_poster_a ON content_clusters(poster_a);
CREATE INDEX idx_content_poster_b ON content_clusters(poster_b);

-- ============================================================
-- 12. GENERAL VIEWS (V4)
-- ============================================================
CREATE OR REPLACE VIEW vw_flagged_content AS
SELECT 
    f.flag_id,
    c.tenant_id,
    c.content_id,
    c.content_text,
    u.username AS author_name,
    f.flag_type,
    f.reason,
    f.status,
    f.report_count,
    f.flagged_at
FROM content_flag f
JOIN content c ON f.content_id = c.content_id
JOIN users u ON c.user_id = u.user_id
WHERE f.status != 'RESOLVED';

CREATE OR REPLACE VIEW vw_audit_log AS
SELECT 
    audit_id,
    action_type,
    action_details,
    reference_type,
    reference_id,
    actor_id,
    actor_type,
    action_timestamp
FROM audit_log
ORDER BY action_timestamp DESC;

CREATE OR REPLACE VIEW vw_top_users AS
SELECT 
    u.user_id,
    u.tenant_id,
    u.username,
    COALESCE(MIN(t.current_trust), 100.0) AS trust_score
FROM users u
LEFT JOIN effective_trust t ON u.user_id = t.user_id
GROUP BY u.user_id, u.tenant_id, u.username
HAVING COALESCE(MIN(t.current_trust), 100.0) > 80.0
ORDER BY trust_score DESC;
