-- V2__tenant_policies.sql

CREATE TABLE tenant_policy (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL REFERENCES tenant_config(tenant_id) ON DELETE CASCADE,
    rule_name VARCHAR(100) NOT NULL,      -- e.g., 'URL_FILTER', 'TOXICITY', 'COORDINATION'
    override_action VARCHAR(50) NOT NULL, -- e.g., 'BYPASS', 'BLOCK', 'REVIEW'
    condition_json JSONB,                 -- e.g., {"min_spam_trust": 80, "min_account_age_days": 30}
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tenant_policy_tenant_id ON tenant_policy(tenant_id);

-- Insert a sample policy for the GLOBAL tenant (URLs are allowed if account is > 30 days old and spam trust > 80)
INSERT INTO tenant_policy (tenant_id, rule_name, override_action, condition_json)
VALUES (
    'GLOBAL', 
    'URL_FILTER', 
    'BYPASS', 
    '{"min_spam_trust": 80, "min_account_age_days": 30}'
);
