-- V2__core_schema.sql

-- ============================================================
-- 1. USERS
-- ============================================================
CREATE TABLE users (
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          VARCHAR(100) NOT NULL,
    external_user_id   VARCHAR(100) NOT NULL,
    username           VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    status             VARCHAR(50)  DEFAULT 'ACTIVE',
    -- Shadow-ban flag. Set by trigger when trust_score < tenant_config.shadow_ban_threshold.
    -- User sees their own posts; public does not.
    is_visible         BOOLEAN      DEFAULT TRUE,
    account_created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, external_user_id)
);

-- ============================================================
-- 2. CONTENT
-- ============================================================
CREATE TABLE content (
    content_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    VARCHAR(100) NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_text TEXT   NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    -- SHA-256 of normalised text (lowercased, stripped whitespace/punctuation).
    -- No UNIQUE constraint: duplicates allowed but caught by BEFORE INSERT trigger within 24h window.
    content_hash VARCHAR(255) NOT NULL,
    -- Per-content visibility flag: allows hiding a single post without shadow-banning the author.
    is_visible   BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS on CONTENT
ALTER TABLE content ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 3. REPORT
-- ============================================================
CREATE TABLE report (
    report_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id       BIGINT NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
    reporter_id      BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    report_reason    TEXT   NOT NULL,
    status           VARCHAR(50) DEFAULT 'PENDING',
    reported_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    -- pgcrypto-hashed IP. Raw IPs are never persisted (GDPR compliance).
    reporter_ip_hash VARCHAR(255)
);

-- Enable RLS on REPORT
ALTER TABLE report ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 4. CONTENT_FLAG
-- ============================================================
CREATE TABLE content_flag (
    flag_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id   BIGINT NOT NULL REFERENCES content(content_id) ON DELETE CASCADE,
    flag_type    VARCHAR(50) NOT NULL,
    reason       TEXT   NOT NULL,
    -- State machine: PENDING → REVIEWED → APPEALED → RESOLVED
    -- 'resolved' BOOLEAN removed: status = 'RESOLVED' is the single source of truth.
    status       VARCHAR(50) DEFAULT 'PENDING',
    report_count INT DEFAULT 0,
    flagged_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 5. VIOLATION
-- ============================================================
CREATE TABLE violation (
    violation_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flag_id        BIGINT NOT NULL REFERENCES content_flag(flag_id) ON DELETE CASCADE,
    user_id        BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    violation_type VARCHAR(50) NOT NULL,
    severity_level INT DEFAULT 1,
    violation_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 6. TRUST_SCORE
-- ============================================================
CREATE TABLE trust_score (
    user_id          BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    trust_score      DECIMAL(5,2) DEFAULT 100.00,
    violation_count  INT DEFAULT 0,
    accurate_reports INT DEFAULT 0,
    last_updated     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 7. BANNED_WORD
-- ============================================================
CREATE TABLE banned_word (
    word_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      VARCHAR(100) NOT NULL DEFAULT 'GLOBAL',
    keyword        VARCHAR(255) NOT NULL,
    -- EXACT_WORD_ONLY: uses word-boundary regex (\b) — prevents the Scunthorpe problem.
    -- SUBSTRING_ALLOWED: raw substring match for short/unambiguous terms.
    match_type     VARCHAR(50) DEFAULT 'EXACT_WORD_ONLY',
    severity_level INT DEFAULT 1,
    -- ACTIVE: enforced by triggers. PENDING: proposed by N-gram agent, awaiting admin review.
    word_status    VARCHAR(50) DEFAULT 'ACTIVE',
    added_by       VARCHAR(255) DEFAULT 'SYSTEM',
    added_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (tenant_id, keyword)
);

-- ============================================================
-- 8. OUTBOX_EVENT
-- ============================================================
-- processed_at replaces processed BOOLEAN to eliminate the race condition where two concurrent
-- Spring workers could both read the same event before either marks it processed.
-- Workers use: SELECT ... FOR UPDATE SKIP LOCKED to claim events atomically.
--   NULL     = unprocessed (available for pickup)
--   non-NULL = successfully processed (timestamp of completion)
CREATE TABLE outbox_event (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   VARCHAR(255) NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    payload        JSONB NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    processed_at   TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

-- ============================================================
-- 9. AUDIT_LOG
-- ============================================================
-- actor_id / actor_type added: who performed the action matters more than what changed
-- for a moderation audit trail. Immutability enforced by a trigger in Phase 2.
-- actor_type values: 'TRIGGER' | 'SYSTEM' | 'ADMIN' | 'APP_USER'
CREATE TABLE audit_log (
    audit_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type      VARCHAR(255) NOT NULL,
    action_details   TEXT,
    reference_type   VARCHAR(255) NOT NULL,
    reference_id     VARCHAR(255) NOT NULL,
    actor_id         BIGINT,     -- NULL for trigger/system-initiated actions
    actor_type       VARCHAR(50) DEFAULT 'SYSTEM',
    action_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 10. TENANT_CONFIG
-- ============================================================
-- Per-tenant tunable thresholds and scoring weights.
-- Eliminates hardcoded magic numbers from trigger logic — triggers READ from this table.
-- Phase 6+: the ML weight tuner writes back to the weight_* columns after admin approval.
--           Hard bounds enforced in application layer: weights in [0.5, 15.0], max ±20% change per cycle.
CREATE TABLE tenant_config (
    tenant_id                 VARCHAR(100) PRIMARY KEY,
    -- Trust score formula weights (used by recalculate_trust_score stored procedure)
    weight_accurate_reports   DECIMAL(5,2) DEFAULT 5.0,
    weight_severity           DECIMAL(5,2) DEFAULT 1.0,
    weight_account_age        DECIMAL(5,2) DEFAULT 10.0,
    -- Moderation thresholds (read by triggers and Spring @Scheduled workers)
    shadow_ban_threshold      INT          DEFAULT 10,    -- trust_score below this → is_visible = false
    report_threshold          INT          DEFAULT 3,     -- reports within 7 days → auto-flag content
    burst_limit               INT          DEFAULT 3,     -- max posts per minute (burst rate limit)
    sustained_limit           INT          DEFAULT 10,    -- max posts per hour (sustained rate limit)
    -- Fuzzy matching sensitivity: lower = more aggressive. Tune per-community.
    trgm_similarity_threshold DECIMAL(3,2) DEFAULT 0.35,
    created_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed a GLOBAL fallback config row (used by triggers when no tenant-specific row exists)
INSERT INTO tenant_config (tenant_id) VALUES ('GLOBAL');

-- ============================================================
-- 11. INDEXES
-- ============================================================

-- content: duplicate-detection hash lookup, time-window queries, per-user and per-tenant queries
CREATE INDEX idx_content_hash       ON content(content_hash);
CREATE INDEX idx_content_created_at ON content(created_at DESC);
CREATE INDEX idx_content_user_id    ON content(user_id);
CREATE INDEX idx_content_tenant_id  ON content(tenant_id);

-- report: per-content report count, per-reporter swatter defense, time-window queries
CREATE INDEX idx_report_content_id  ON report(content_id);
CREATE INDEX idx_report_reporter_id ON report(reporter_id);
CREATE INDEX idx_report_reported_at ON report(reported_at DESC);

-- content_flag: admin dashboard queue (only active flags), state machine lookups
CREATE INDEX idx_flag_content_id    ON content_flag(content_id);
CREATE INDEX idx_flag_status        ON content_flag(status) WHERE status != 'RESOLVED';

-- violation: trust score recalculation joins
CREATE INDEX idx_violation_user_id  ON violation(user_id);

-- banned_word: GIN trigram index — CRITICAL for pg_trgm fuzzy matching to stay < 100ms at scale
CREATE INDEX idx_banned_word_trgm   ON banned_word USING GIN (keyword gin_trgm_ops);
CREATE INDEX idx_banned_word_tenant ON banned_word(tenant_id);

-- outbox_event: partial index on unprocessed events only — keeps the worker polling index tiny
CREATE INDEX idx_outbox_unprocessed ON outbox_event(created_at ASC) WHERE processed_at IS NULL;

-- users: tenant-scoped queries, trust score checks
CREATE INDEX idx_users_tenant_id    ON users(tenant_id);
